/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'author' : string,
  'timestamp' : Time,
}
export interface CommentUpdateRequest { 'content' : string, 'author' : string }
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'likes' : bigint,
  'timestamp' : Time,
  'comments' : Array<Comment>,
}
export interface PostUpdateRequest {
  'title' : string,
  'content' : string,
  'author' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommentToPost' : ActorMethod<[bigint, CommentUpdateRequest], [] | [Post]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'consumeConsultation' : ActorMethod<[Principal], boolean>,
  'createPost' : ActorMethod<[PostUpdateRequest], Post>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPostById' : ActorMethod<[bigint], [] | [Post]>,
  'getRemainingFreeConsultations' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], [] | [bigint]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unlikePost' : ActorMethod<[bigint], [] | [bigint]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];