/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CommentUpdateRequest = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'timestamp' : Time,
  'comments' : IDL.Vec(Comment),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostUpdateRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommentToPost' : IDL.Func(
      [IDL.Nat, CommentUpdateRequest],
      [IDL.Opt(Post)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'consumeConsultation' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'createPost' : IDL.Func([PostUpdateRequest], [Post], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getRemainingFreeConsultations' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CommentUpdateRequest = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'timestamp' : Time,
    'comments' : IDL.Vec(Comment),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostUpdateRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommentToPost' : IDL.Func(
        [IDL.Nat, CommentUpdateRequest],
        [IDL.Opt(Post)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'consumeConsultation' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'createPost' : IDL.Func([PostUpdateRequest], [Post], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getRemainingFreeConsultations' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  });
};

export const init = ({ IDL }) => { return []; };